name: PnP

on:
  push:
    branches:
      - github-actions

jobs:
  pnp:
    name: PnP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create project
        run: git clone https://github.com/gridsome/gridsome-starter-default.git pnp-e2e
      - name: Configure Yarn
        working-directory: ./pnp-e2e
        run: |
          touch yarn.lock
          yarn set version 2
          yarn config set pnpFallbackMode none
          yarn config set compressionLevel 0
      - name: Get cache directory
        working-directory: ./pnp-e2e
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Link packages
        working-directory: ./pnp-e2e
        run: yarn link -A ../
      - name: Build
        working-directory: ./pnp-e2e
        run: yarn build
